### ISSUE TITLE
Remove random.seed function from inner function

### ISSUE THREAD

**Issue by yodigi7** [mm103434/Simple_Simulation#10]
The random.seed function should only be called once at the beginning of the project in order to be more efficient and work the way it is intended.

https://docs.python.org/3/library/random.html

**Comment by KIRA009** [comment]
The random.seed() function ensures that the number generated is always truly random, which somewhat resembles real life simulation

**Comment by yodigi7** [comment]
Yes, however, according to the docs, it is used to initialize the random number generation which only needs to occur once. The purpose of the function is because the random number generator needs a starting number in order to generate the next number and since the random number generator is the same across the program, it is best practice to only initialize it once. Also it makes it easier when debugging since you can set the seed to get the same result over multiple runs however if it is setup this way there are more places to change it and would also remove the randomness.

Try it out, at the start of the program call random.seed once and it will still generate all random values throughout the program.
