### ISSUE TITLE
Change the way all events are calculated

### ISSUE THREAD

**Issue by ShadowMuffin** [mm103434/Simple_Simulation#15]
So I've taken a look at the main.py, and to be honest, once we add more functions and stuff, it will all get garbled up in timers and following the flow will be quite an undertaking.

My offer is instead to run a single day, and in that day, calculate deaths, newborns, disasters and other stuff that people may add.

That way it will be cleaner, and perhaps a little faster to run.

**Comment by KIRA009** [comment]
True that, we can first sort out the features, then we will come back to breaking the entire duration into days or hours. I will try to keep a lookout if the code starts to get messy. Great observation

**Comment by mm103434** [comment]
Done. Everything is split into days now.
